version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      #      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minha-aplicacao
    restart: always
    environment:
      NODE_ENV: development
    command: ["sh", "-c", "sleep 9 && npm run dev"]
    depends_on:
      - db
    ports:
      - 3000:3000
